// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	sqlc "github.com/jabella1/stock-ratings-service/internal/features/stock/infra/db/sqlc"
	mock "github.com/stretchr/testify/mock"
)

// DatabaseTransaction is an autogenerated mock type for the DatabaseTransaction type
type DatabaseTransaction struct {
	mock.Mock
}

// Commit provides a mock function with given fields: _a0
func (_m *DatabaseTransaction) Commit(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Queries provides a mock function with no fields
func (_m *DatabaseTransaction) Queries() *sqlc.Queries {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Queries")
	}

	var r0 *sqlc.Queries
	if rf, ok := ret.Get(0).(func() *sqlc.Queries); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.Queries)
		}
	}

	return r0
}

// Rollback provides a mock function with given fields: _a0
func (_m *DatabaseTransaction) Rollback(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDatabaseTransaction creates a new instance of DatabaseTransaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseTransaction {
	mock := &DatabaseTransaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
