// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Float is an autogenerated mock type for the Float type
type Float struct {
	mock.Mock
}

// NewFloat creates a new instance of Float. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFloat(t interface {
	mock.TestingT
	Cleanup(func())
}) *Float {
	mock := &Float{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
