// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	query "github.com/jabella1/stock-ratings-service/internal/features/stock/app/query"
)

// GetListStockRatingQueryHandler is an autogenerated mock type for the GetListStockRatingQueryHandler type
type GetListStockRatingQueryHandler struct {
	mock.Mock
}

// GetListStockRating provides a mock function with given fields: _a0, getListStockRatingQuery
func (_m *GetListStockRatingQueryHandler) GetListStockRating(_a0 context.Context, getListStockRatingQuery *query.GetListStockRatingQuery) (*query.GetListStockRatingResult, error) {
	ret := _m.Called(_a0, getListStockRatingQuery)

	if len(ret) == 0 {
		panic("no return value specified for GetListStockRating")
	}

	var r0 *query.GetListStockRatingResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.GetListStockRatingQuery) (*query.GetListStockRatingResult, error)); ok {
		return rf(_a0, getListStockRatingQuery)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.GetListStockRatingQuery) *query.GetListStockRatingResult); ok {
		r0 = rf(_a0, getListStockRatingQuery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*query.GetListStockRatingResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.GetListStockRatingQuery) error); ok {
		r1 = rf(_a0, getListStockRatingQuery)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetListStockRatingQueryHandler creates a new instance of GetListStockRatingQueryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetListStockRatingQueryHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetListStockRatingQueryHandler {
	mock := &GetListStockRatingQueryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
