// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	query "github.com/jabella1/stock-ratings-service/internal/features/stock/app/query"
)

// GetStockRatingByTickerQueryHandler is an autogenerated mock type for the GetStockRatingByTickerQueryHandler type
type GetStockRatingByTickerQueryHandler struct {
	mock.Mock
}

// GetStockRatingByTicker provides a mock function with given fields: _a0, getStockRatingByTickerQuery
func (_m *GetStockRatingByTickerQueryHandler) GetStockRatingByTicker(_a0 context.Context, getStockRatingByTickerQuery *query.GetStockRatingByTickerQuery) (*query.GetStockRatingByTickerResult, error) {
	ret := _m.Called(_a0, getStockRatingByTickerQuery)

	if len(ret) == 0 {
		panic("no return value specified for GetStockRatingByTicker")
	}

	var r0 *query.GetStockRatingByTickerResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *query.GetStockRatingByTickerQuery) (*query.GetStockRatingByTickerResult, error)); ok {
		return rf(_a0, getStockRatingByTickerQuery)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.GetStockRatingByTickerQuery) *query.GetStockRatingByTickerResult); ok {
		r0 = rf(_a0, getStockRatingByTickerQuery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*query.GetStockRatingByTickerResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.GetStockRatingByTickerQuery) error); ok {
		r1 = rf(_a0, getStockRatingByTickerQuery)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetStockRatingByTickerQueryHandler creates a new instance of GetStockRatingByTickerQueryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetStockRatingByTickerQueryHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetStockRatingByTickerQueryHandler {
	mock := &GetStockRatingByTickerQueryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
