// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	sqlc "github.com/jabella1/stock-ratings-service/internal/features/stock/infra/db/sqlc"
	mock "github.com/stretchr/testify/mock"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

// CountStockRatings provides a mock function with given fields: ctx, arg
func (_m *Querier) CountStockRatings(ctx context.Context, arg sqlc.CountStockRatingsParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CountStockRatings")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CountStockRatingsParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CountStockRatingsParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.CountStockRatingsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStockRatingByTicker provides a mock function with given fields: ctx, ticker
func (_m *Querier) GetStockRatingByTicker(ctx context.Context, ticker string) (sqlc.ChallengeStockRating, error) {
	ret := _m.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetStockRatingByTicker")
	}

	var r0 sqlc.ChallengeStockRating
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlc.ChallengeStockRating, error)); ok {
		return rf(ctx, ticker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlc.ChallengeStockRating); ok {
		r0 = rf(ctx, ticker)
	} else {
		r0 = ret.Get(0).(sqlc.ChallengeStockRating)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertStockRatingHistory provides a mock function with given fields: ctx, arg
func (_m *Querier) InsertStockRatingHistory(ctx context.Context, arg sqlc.InsertStockRatingHistoryParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertStockRatingHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.InsertStockRatingHistoryParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListStockRatings provides a mock function with given fields: ctx, arg
func (_m *Querier) ListStockRatings(ctx context.Context, arg sqlc.ListStockRatingsParams) ([]sqlc.ChallengeStockRating, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListStockRatings")
	}

	var r0 []sqlc.ChallengeStockRating
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.ListStockRatingsParams) ([]sqlc.ChallengeStockRating, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.ListStockRatingsParams) []sqlc.ChallengeStockRating); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.ChallengeStockRating)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.ListStockRatingsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertStockRating provides a mock function with given fields: ctx, arg
func (_m *Querier) UpsertStockRating(ctx context.Context, arg sqlc.UpsertStockRatingParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertStockRating")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpsertStockRatingParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpsertStockRatingParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.UpsertStockRatingParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
