// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	command "github.com/jabella1/stock-ratings-service/internal/features/stock/app/command"

	mock "github.com/stretchr/testify/mock"

	wrapper "github.com/jabella1/stock-ratings-service/internal/features/common/wrapper"
)

// SaveStockRatingCommandHandler is an autogenerated mock type for the SaveStockRatingCommandHandler type
type SaveStockRatingCommandHandler struct {
	mock.Mock
}

// SaveStockRating provides a mock function with given fields: _a0, saveStockRatingCommand
func (_m *SaveStockRatingCommandHandler) SaveStockRating(_a0 context.Context, saveStockRatingCommand *command.SaveStockRatingCommand) (*wrapper.Response[command.SaveStockRatingResult], error) {
	ret := _m.Called(_a0, saveStockRatingCommand)

	if len(ret) == 0 {
		panic("no return value specified for SaveStockRating")
	}

	var r0 *wrapper.Response[command.SaveStockRatingResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *command.SaveStockRatingCommand) (*wrapper.Response[command.SaveStockRatingResult], error)); ok {
		return rf(_a0, saveStockRatingCommand)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *command.SaveStockRatingCommand) *wrapper.Response[command.SaveStockRatingResult]); ok {
		r0 = rf(_a0, saveStockRatingCommand)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wrapper.Response[command.SaveStockRatingResult])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *command.SaveStockRatingCommand) error); ok {
		r1 = rf(_a0, saveStockRatingCommand)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSaveStockRatingCommandHandler creates a new instance of SaveStockRatingCommandHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSaveStockRatingCommandHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *SaveStockRatingCommandHandler {
	mock := &SaveStockRatingCommandHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
