// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/jabella1/stock-ratings-service/internal/features/stock/domain/entities"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/jabella1/stock-ratings-service/internal/features/stock/domain/pagination"

	repositories "github.com/jabella1/stock-ratings-service/internal/features/stock/domain/repositories"

	unitofwork "github.com/jabella1/stock-ratings-service/internal/features/stock/domain/unitOfWork"
)

// StockRatingRepository is an autogenerated mock type for the StockRatingRepository type
type StockRatingRepository struct {
	mock.Mock
}

// GetListStockRating provides a mock function with given fields: _a0, search, pageSize, pageNumber, orderBy, orderDirection, minUpside, minPrice, maxPrice
func (_m *StockRatingRepository) GetListStockRating(_a0 context.Context, search *string, pageSize *int32, pageNumber *int32, orderBy string, orderDirection string, minUpside float32, minPrice float64, maxPrice float64) (*pagination.PaginatedList[entities.StockRating], error) {
	ret := _m.Called(_a0, search, pageSize, pageNumber, orderBy, orderDirection, minUpside, minPrice, maxPrice)

	if len(ret) == 0 {
		panic("no return value specified for GetListStockRating")
	}

	var r0 *pagination.PaginatedList[entities.StockRating]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string, *int32, *int32, string, string, float32, float64, float64) (*pagination.PaginatedList[entities.StockRating], error)); ok {
		return rf(_a0, search, pageSize, pageNumber, orderBy, orderDirection, minUpside, minPrice, maxPrice)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string, *int32, *int32, string, string, float32, float64, float64) *pagination.PaginatedList[entities.StockRating]); ok {
		r0 = rf(_a0, search, pageSize, pageNumber, orderBy, orderDirection, minUpside, minPrice, maxPrice)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagination.PaginatedList[entities.StockRating])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string, *int32, *int32, string, string, float32, float64, float64) error); ok {
		r1 = rf(_a0, search, pageSize, pageNumber, orderBy, orderDirection, minUpside, minPrice, maxPrice)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStockRatingByTicker provides a mock function with given fields: _a0, ticker
func (_m *StockRatingRepository) GetStockRatingByTicker(_a0 context.Context, ticker string) (*entities.StockRating, error) {
	ret := _m.Called(_a0, ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetStockRatingByTicker")
	}

	var r0 *entities.StockRating
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.StockRating, error)); ok {
		return rf(_a0, ticker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.StockRating); ok {
		r0 = rf(_a0, ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.StockRating)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveStockRating provides a mock function with given fields: _a0, databaseTransaction, stockRating
func (_m *StockRatingRepository) SaveStockRating(_a0 context.Context, databaseTransaction unitofwork.DatabaseTransaction, stockRating *entities.StockRating) (*repositories.UpsertResult, error) {
	ret := _m.Called(_a0, databaseTransaction, stockRating)

	if len(ret) == 0 {
		panic("no return value specified for SaveStockRating")
	}

	var r0 *repositories.UpsertResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, unitofwork.DatabaseTransaction, *entities.StockRating) (*repositories.UpsertResult, error)); ok {
		return rf(_a0, databaseTransaction, stockRating)
	}
	if rf, ok := ret.Get(0).(func(context.Context, unitofwork.DatabaseTransaction, *entities.StockRating) *repositories.UpsertResult); ok {
		r0 = rf(_a0, databaseTransaction, stockRating)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.UpsertResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, unitofwork.DatabaseTransaction, *entities.StockRating) error); ok {
		r1 = rf(_a0, databaseTransaction, stockRating)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveStockRatingHistory provides a mock function with given fields: _a0, databaseTransaction, stockRatingHistory
func (_m *StockRatingRepository) SaveStockRatingHistory(_a0 context.Context, databaseTransaction unitofwork.DatabaseTransaction, stockRatingHistory *entities.StockRatingHistory) error {
	ret := _m.Called(_a0, databaseTransaction, stockRatingHistory)

	if len(ret) == 0 {
		panic("no return value specified for SaveStockRatingHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, unitofwork.DatabaseTransaction, *entities.StockRatingHistory) error); ok {
		r0 = rf(_a0, databaseTransaction, stockRatingHistory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStockRatingRepository creates a new instance of StockRatingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockRatingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockRatingRepository {
	mock := &StockRatingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
