// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	unitofwork "github.com/jabella1/stock-ratings-service/internal/features/stock/domain/unitOfWork"
	mock "github.com/stretchr/testify/mock"
)

// UnitOfWork is an autogenerated mock type for the UnitOfWork type
type UnitOfWork struct {
	mock.Mock
}

// BeginTransaction provides a mock function with given fields: _a0
func (_m *UnitOfWork) BeginTransaction(_a0 context.Context) (unitofwork.DatabaseTransaction, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 unitofwork.DatabaseTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (unitofwork.DatabaseTransaction, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) unitofwork.DatabaseTransaction); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(unitofwork.DatabaseTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUnitOfWork creates a new instance of UnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnitOfWork {
	mock := &UnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
