// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetStockRatingByTicker(ctx context.Context, ticker string) (ChallengeStockRating, error)
	UpsertStockRating(ctx context.Context, arg UpsertStockRatingParams) error
}

var _ Querier = (*Queries)(nil)
