// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountStockRatings(ctx context.Context, arg CountStockRatingsParams) (int64, error)
	GetStockRatingByTicker(ctx context.Context, ticker string) (ChallengeStockRating, error)
	InsertStockRatingHistory(ctx context.Context, arg InsertStockRatingHistoryParams) error
	ListStockRatings(ctx context.Context, arg ListStockRatingsParams) ([]ChallengeStockRating, error)
	UpsertStockRating(ctx context.Context, arg UpsertStockRatingParams) error
}

var _ Querier = (*Queries)(nil)
