// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock_rating.sql

package sqlc

import (
	"context"
)

const getStockRatingByTicker = `-- name: GetStockRatingByTicker :one
SELECT id, ticker, company, brokerage, action, rating_from, rating_to,
       target_from, target_to, created_at
FROM challenge.stock_rating
WHERE ticker = $1
`

func (q *Queries) GetStockRatingByTicker(ctx context.Context, ticker string) (ChallengeStockRating, error) {
	row := q.db.QueryRow(ctx, getStockRatingByTicker, ticker)
	var i ChallengeStockRating
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Company,
		&i.Brokerage,
		&i.Action,
		&i.RatingFrom,
		&i.RatingTo,
		&i.TargetFrom,
		&i.TargetTo,
		&i.CreatedAt,
	)
	return i, err
}
